version: "3"

services:
  node_app:
    container_name: node_app
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/usr/yousheet
      - /usr/yousheet/node_modules
